#!/bin/bash
set -e

SRC="qst_barrier_2d.c my_mkl_malloc.c"
BIN="qst_barrier_2d"
INPUT_FILE="${1:-input.in}"       # Default input file, or pass via command line

NP=${NP:-1}                       # Number of MPI Ranks (Default: 4)
HEIGHT_SEQ="1 2 3 4 5 6 7 8 9 10" 
WIDTH_SEQ="1 2 3 4 5 6 7 8 9 10" 

RESULTS_DIR="results"
TEMP_RUN_DIR="temp_run_data"

BEST_FIDELITY_OVERALL=0.0

if [ -f /opt/intel/oneapi/setvars.sh ]; then
    source /opt/intel/oneapi/setvars.sh > /dev/null 2>&1 || true
fi

mkdir -p "$RESULTS_DIR"

# ==========================================
# 3. Compilation Step
# ==========================================
COMPILER=$(command -v mpicc || echo "gcc")
echo "==> Compiling source files using $COMPILER..."

$COMPILER -O3 -march=native -ffast-math $SRC \
  -lmkl_intel_lp64 -lmkl_sequential -lmkl_core \
  -lpthread -lm -ldl \
  -o "$BIN"

echo "==> Compilation successful. Running with NP=$NP..."

ny=$(grep -iE "^[[:space:]]*Ny" "$INPUT_FILE" | grep -oE "[0-9]+" | head -n 1)
if [ -z "$ny" ]; then
    echo "Warning: Ny not found in $INPUT_FILE."
    exit 1
fi

iran_value=$grep -iE "^[[:space:]]*iran" "$INPUT_FILE" | grep -oE "[0-9]+" | head -n 1
if [ -z "$iran_value" ]; then
    echo "Warning: iran not found in $INPUT_FILE."
    exit 1
fi

for bh in $HEIGHT_SEQ; do
    for bw in $WIDTH_SEQ; do
        # Skip if barrier width exceeds the width of the lattice (Ny)
        if [ "$bw" -gt "$ny" ]; then
            continue
        fi

        TEMP_INPUT="temp_input.in"
        cp "$INPUT_FILE" "$TEMP_INPUT"

        # Update iran, height, and width in temp_input.in
        sed -i "s/^[[:space:]]*iran.*/iran = $iran_value/" "$TEMP_INPUT"
        sed -i "s/^[[:space:]]*barrier_height.*/barrier_height = $bh/" "$TEMP_INPUT"
        sed -i "s/^[[:space:]]*barrier_width.*/barrier_width = $bw/" "$TEMP_INPUT"

        echo -e "\n--------------------------------------------------"
        echo "Running simulation: Height = $bh | Width = $bw | iran = $iran_value | NP = $NP"
        echo "--------------------------------------------------"

        # REMOVE stale output files from previous iteration before running
        rm -f fidelity_history.txt

        # Execute simulation explicitly using TEMP_INPUT
        mpirun -n "$NP" ./"$BIN" "$TEMP_INPUT" > /dev/null

        # Check if a new fidelity_history.txt was generated
        if [ -f "fidelity_history.txt" ]; then
            # Extract peak fidelity from the FRESH run output
            MAX_RUN_FIDELITY=$(awk -F',' 'NR>1 {if ($3 > max) max=$3} END {print max}' fidelity_history.txt 2>/dev/null)
            MAX_RUN_FIDELITY="${MAX_RUN_FIDELITY:-0.0}"
            
        else
            echo "WARNING: fidelity_history.txt was not generated by $BIN!"
            MAX_RUN_FIDELITY="0.0"
        fi

        echo "--> Maximum fidelity achieved: $MAX_RUN_FIDELITY"

        # Move generated output files directly to results directory
        mv gmon.out* *.dat *.csv qst_*.out *.out "$RESULTS_DIR/" 2>/dev/null || true
        rm -f "$TEMP_INPUT"

        # Render graphviz visualization if dot is present
        if command -v dot >/dev/null 2>&1 && [ -f lattice.dot ]; then
            dot -Tpng lattice.dot -o "$RESULTS_DIR/lattice_h${bh}_w${bw}.png"
            rm -f lattice.dot
        fi
    done
done
